---
- name: Keytool
  hosts: all
  become: yes

  vars:

    alias_list:
      - newkey1
      - newkey2

  handlers:

  tasks:

    - name: Read password from file
      slurp:
        src: "/root/password_file"
      no_log: true
      register: file_content

    - set_fact: 
        keystore_password: "{{ file_content['content'] | b64decode | trim }}"
      no_log: true

    - name: Check if keystore password is the default one
      command: "keytool -list -keystore vault.keystore -storepass changeit"
      register: check_if_default
      ignore_errors: true
      changed_when: false

    - debug:
        msg: "{{ check_if_default }}"

    - name: Change keystore password
      command: "keytool -storepasswd -keystore /root/vault.keystore -new {{ keystore_password }} -storepass changeit"
      environment:
        STORE_PASS: "{{ keystore_password }}"
      when: check_if_default.rc == 0
      
