---
- name: Keytool
  hosts: all
  become: yes

  vars:

    alias_list:
      - test11
      - test12
      - test13

  handlers:

  tasks:

    - name: Read password from file
      slurp:
        src: "/root/password_file" # /opt/openidm/openidm/security/keystorepass
      no_log: true
      register: file_content

    - set_fact: 
        keystore_password: "{{ file_content['content'] | b64decode | trim }}"
      no_log: true

    - name: Check if we're still using default password, if so, create new a change keystore & keys password
      block:

      - name: Generate new password
        set_fact:
          new_password: "{{ lookup('password', '/dev/null length=20 chars=ascii_letters') }}"

      - name: Copy new password to file
        copy:
          dest: /root/password_file ## /opt/openidm/openidm/security/keystorepass
          content: "{{ new_password }}"

      - name: Change keystore password
        command: "keytool -storepasswd -keystore /root/vault.keystore -new $STORE_PASS -storepass changeit"
        environment:
          STORE_PASS: "{{ new_password }}"

      - name: Change key password
        command: "keytool -keypasswd -alias {{ item }} -keystore /root/vault.keystore -storepass $STORE_PASS -keypass changeit -new $STORE_PASS"
        environment:
          STORE_PASS: "{{ new_password }}"
        loop: "{{ alias_list }}"
      
      when: keystore_password == "changeit"
